import pandas as pd
import os
import glob


def generate_master_table(root_path):
    """
    Collects individual metrics_summary.csv files and compiles them into a master report.
    """
    # 1. Look for all 'metrics_summary.csv' files generated by the previous script
    search_pattern = os.path.join(root_path, "**", "metrics_summary.csv")
    metrics_files = glob.glob(search_pattern, recursive=True)

    if not metrics_files:
        print(
            "No metrics_summary.csv files found. Please run the calculation script first."
        )
        return

    all_experiment_results = []

    for file_path in metrics_files:
        try:
            # Read the metrics for this specific experiment
            df = pd.read_csv(file_path)

            # Extract the experiment name from the folder structure
            # Example: 'final_background/experiment_01/metrics_summary.csv' -> 'experiment_01'
            folder_parts = os.path.normpath(file_path).split(os.sep)
            # The experiment name is typically the folder immediately containing the file
            experiment_name = folder_parts[-2]

            # Insert the experiment name as the first column
            df.insert(0, "experiment_name", experiment_name)

            all_experiment_results.append(df)

        except Exception as e:
            print(f"Error reading {file_path}: {e}")

    if all_experiment_results:
        # Combine all experiments into one large DataFrame
        master_df = pd.concat(all_experiment_results, ignore_index=True)

        # Save the master table directly under the root 'final_background' folder
        output_path = os.path.join(root_path, "master_experiment_metrics.csv")
        master_df.to_csv(output_path, index=False)

        print("-" * 30)
        print(f"Master report generated successfully!")
        print(f"Location: {output_path}")
        print(f"Total experiments compiled: {len(all_experiment_results)}")
        print("-" * 30)

        # Display the first few rows of the master table for a quick check
        print(master_df.head())
    else:
        print("No data collected.")


if __name__ == "__main__":
    # The root directory where your experiments live
    BASE_DIR = "final_background"
    generate_master_table(BASE_DIR)
